name: Docker Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from helm chart
        run: |
          VERSION=$(grep "version:" ./helm/Chart.yaml | cut -d: -f2 | tr -d ' ')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version is $VERSION"

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./docker/frontend/Dockerfile

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}_api
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./docker/api/Dockerfile

  # push-helm-chart:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Push Helm Chart
  #       uses: ./.github/actions/push-to-helm
  #       with:
  #         app-repo-token: ${{ secrets.GPAT_TOKEN }}

  # success-message:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #     - push-helm-chart
  #   steps:
  #     - name: Send Discord Message
  #       uses: jaypyles/discord-webhook-action@v1.0.0
  #       with:
  #         webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
  #         content: "Scraperr Successfully Built Docker Images"
  #         username: "Scraperr CI"
  #         embed-title: "✅ Deployment Status"
  #         embed-description: "Scraperr successfully built docker images."
  #         embed-color: 3066993 # Green
  #         embed-footer-text: "Scraperr CI"
  #         embed-timestamp: ${{ github.event.head_commit.timestamp }}
